### ISSUE TITLE
Default page styling

### ISSUE THREAD

**Issue by gehalber** [everythingtype/corrado#10]
@halfempty @KyleETC 
Can you set the default template to have the same h settings and paragraph settings as the case studies? That will get us closer pretty quickly.

**Comment by halfempty** [comment]
@gehalber Take a look and let me know further tweaks? More space around the title? Something specific for headings?

https://corrado.wpengine.com/privacy-policy/
https://corrado.wpengine.com/disclosure/

**Comment by gehalber** [comment]
Yes, let's do more space around title: 
margin: 3.2rem 0 8.4rem 0

**Comment by halfempty** [comment]
@gehalber Done.

Also, I wanted to add some semantics to the HTML headings here, so I put in a spot of Trio. But maybe you'd like something other / specific there?

![image](https://user-images.githubusercontent.com/775543/44601707-f6aeee00-a7a2-11e8-8d26-95a006f6f16f.png)

**Comment by gehalber** [comment]
I made these H3's, which you had set as italic. These seem kind of nice, so let's keep this way for now.
