### ISSUE TITLE
Homepage copy

### ISSUE THREAD

**Issue by gehalber** [everythingtype/corrado#11]
@halfempty @KyleETC 
We have slightly edited copy for the homepage. Pasting below for you.

**We are the Corrado Financial Group**
We help our clients plan and chart their financial futures—so that they can live more fully in the present.

We began as an accounting firm. In the two decades since, we’ve come to understand that many of our clients need more than someone to file their tax returns—they need advisors who understand the full scope of their financial lives. They need guidance on their investment portfolio, help with planning for retirement, direction on writing their wills, their prenups, their insurances.

Our relationships-first approach to financial planning gives our clients the freedom to realize their brightest futures. 

**Contact Us**
Interested in learning more about our services? Speak with a financial advisor to see if we’re a good fit for you.

**Comment by halfempty** [comment]
Done
