### ISSUE TITLE
Order of Advisors landing page

### ISSUE THREAD

**Issue by gehalber** [everythingtype/corrado#12]
@halfempty @KyleETC 
The professional abbreviations should be small caps regular/normal

<img width="311" alt="screen shot 2018-08-18 at 1 09 19 am" src="https://user-images.githubusercontent.com/6076488/44296033-9a6c3b80-a283-11e8-98b5-b6ceb16ac359.png">

**Comment by gehalber** [comment]
Also, why is Frank Cavuoto first on the landing page when in the list order on pages in backend, he's not first?

**Comment by halfempty** [comment]
Let's log both small-caps changes in issue #13.
The ordering issue is fixed.
