### ISSUE TITLE
Small caps for professional abbreviations

### ISSUE THREAD

**Issue by gehalber** [everythingtype/corrado#13]
@halfempty @KyleETC 
the professional abbreviation needs to go next to name

can you set them so their true small caps for william display?

<img width="781" alt="screen shot 2018-08-18 at 1 14 25 am" src="https://user-images.githubusercontent.com/6076488/44296047-123a6600-a284-11e8-9599-2125efee4103.png">

**Comment by halfempty** [comment]
@gehalber There's a complication in doing this. I've written to Typotheque for advice.

**Comment by halfempty** [comment]
@gehalber Okay, progress! I've got small-caps going, and it looks like:

![image](https://user-images.githubusercontent.com/775543/44372601-53ac5a80-a4aa-11e8-904a-7cbaa79072c2.png)
and
![image](https://user-images.githubusercontent.com/775543/44372741-efd66180-a4aa-11e8-9a4c-1f4ff2e91a24.png)

How's the size? They're as tall as the lowercase x-height. Would you like that tweaked?

**Comment by gehalber** [comment]
@halfempty 
Cool. I just bought william display regular because I think we should use the regular small caps instead of bold. I added it to the typotheque project. 

Nerdy I know!

**Comment by halfempty** [comment]
@gehalber Like this?

![image](https://user-images.githubusercontent.com/775543/44606564-2108a780-a7b3-11e8-91bb-9668185d658f.png)

![image](https://user-images.githubusercontent.com/775543/44606568-28c84c00-a7b3-11e8-9ba0-e53c3316f402.png)

**Comment by gehalber** [comment]
Looks great!
