### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by gehalber** [everythingtype/corrado#15]
@halfempty 
Does search work yet?

**Comment by halfempty** [comment]
@gehalber Not yet! I don't see in the Illustrator an indication of how you'd like it to behave. Would y'all like to design that, or would you like me to propose something?

**Comment by halfempty** [comment]
@gehalber Wait, nevermind, there it is. On it.

**Comment by halfempty** [comment]
@gehalber Y'know, I've begun work on search... but it does occur to me that there's so few pages on this site, and they're all accessible via the top nav, that keyword Search probably won't really be very useful. I can keep working on it, but IMO it could be tabled 'till case studies or something like that comes into play.

**Comment by gehalber** [comment]
Agreed!

**Comment by gehalber** [comment]
Let's remove and replace with Home for now.

**Comment by halfempty** [comment]
Done
