### ISSUE TITLE
Webfonts

### ISSUE THREAD

**Issue by halfempty** [everythingtype/corrado#2]
@gehalber Just confirming--- should I pick up the webfonts? Or have y'all already?

**Comment by gehalber** [comment]
@halfempty 
I got William and added you to web service. I took at stab at weight numbering (100, 200, 300), but obviously you should tweak to your normal specifications. I think these are the only fonts we really need for now. I'll look into Trio now.

**Comment by halfempty** [comment]
@gehalber Hi Geoff! I got into Typotheque for William, but I don't see the web files Trio? (Maybe you meant to attach them but didn't?)

**Comment by gehalber** [comment]
Just sent to you!
