### ISSUE TITLE
Logo transition

### ISSUE THREAD

**Issue by halfempty** [everythingtype/corrado#3]
@gehalber In the mockups I'm seeing that the logo changes on scroll-- either to a monograph or a wordmark. How do you want those transitions? Snap from one to another? Crossfade?

**Comment by gehalber** [comment]
@halfempty 
You scroll down and it scrolls with the page. If you scroll up, it comes in from the top.
Reference: www.instrument.com/

**Comment by halfempty** [comment]
@gehalber I just pushed some changes to the staging site. I think this issue, the movement of the top bar, is the main piece remaining. Please feel free to make issues for any other things that catch your eye

**Comment by halfempty** [comment]
@gehalber Updates pushed to the Corrado staging site. I've done some work on the movement of the top bar. Take a look and let me know your feedback? I'll send you the pw in an email
