### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by gehalber** [everythingtype/corrado#35]
@halfempty 
I can't change the homepage, but this graph needs to be updated...

<img width="1469" alt="Screen Shot 2020-06-15 at 4 48 52 PM" src="https://user-images.githubusercontent.com/6076488/84704675-315db980-af28-11ea-94cc-915a2d71d952.png">

to...

They need guidance on their investment portfolio, help with planning for retirement, direction on writing their wills, and assistance in identifying insurance needs.

**Comment by halfempty** [comment]
Done
